# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI_files/ui_default_signal_settings_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(367, 288)
        self.verticalLayout = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.line_2 = QtWidgets.QFrame(Dialog)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.verticalLayout.addWidget(self.line_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_3.addWidget(self.label_2)
        self.spinBox_pre_window_msec = QtWidgets.QSpinBox(Dialog)
        self.spinBox_pre_window_msec.setMaximum(1000)
        self.spinBox_pre_window_msec.setProperty("value", 50)
        self.spinBox_pre_window_msec.setObjectName("spinBox_pre_window_msec")
        self.horizontalLayout_3.addWidget(self.spinBox_pre_window_msec)
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_3.addWidget(self.label_3)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_5 = QtWidgets.QLabel(Dialog)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_2.addWidget(self.label_5)
        self.spinBox_post_window_msec = QtWidgets.QSpinBox(Dialog)
        self.spinBox_post_window_msec.setMaximum(1000)
        self.spinBox_post_window_msec.setProperty("value", 50)
        self.spinBox_post_window_msec.setObjectName("spinBox_post_window_msec")
        self.horizontalLayout_2.addWidget(self.spinBox_post_window_msec)
        self.label_4 = QtWidgets.QLabel(Dialog)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_2.addWidget(self.label_4)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_6 = QtWidgets.QLabel(Dialog)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_4.addWidget(self.label_6)
        self.radioButton_win_shape_tukey = QtWidgets.QRadioButton(Dialog)
        self.radioButton_win_shape_tukey.setChecked(True)
        self.radioButton_win_shape_tukey.setObjectName("radioButton_win_shape_tukey")
        self.buttonGroup = QtWidgets.QButtonGroup(Dialog)
        self.buttonGroup.setObjectName("buttonGroup")
        self.buttonGroup.addButton(self.radioButton_win_shape_tukey)
        self.horizontalLayout_4.addWidget(self.radioButton_win_shape_tukey)
        self.doubleSpinBox_tukey_param = QtWidgets.QDoubleSpinBox(Dialog)
        self.doubleSpinBox_tukey_param.setDecimals(1)
        self.doubleSpinBox_tukey_param.setMaximum(1.0)
        self.doubleSpinBox_tukey_param.setSingleStep(0.1)
        self.doubleSpinBox_tukey_param.setProperty("value", 1.0)
        self.doubleSpinBox_tukey_param.setObjectName("doubleSpinBox_tukey_param")
        self.horizontalLayout_4.addWidget(self.doubleSpinBox_tukey_param)
        self.radioButton_win_shape_square = QtWidgets.QRadioButton(Dialog)
        self.radioButton_win_shape_square.setObjectName("radioButton_win_shape_square")
        self.buttonGroup.addButton(self.radioButton_win_shape_square)
        self.horizontalLayout_4.addWidget(self.radioButton_win_shape_square)
        self.radioButton_win_shape_log = QtWidgets.QRadioButton(Dialog)
        self.radioButton_win_shape_log.setObjectName("radioButton_win_shape_log")
        self.buttonGroup.addButton(self.radioButton_win_shape_log)
        self.horizontalLayout_4.addWidget(self.radioButton_win_shape_log)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        spacerItem = QtWidgets.QSpacerItem(20, 96, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.line = QtWidgets.QFrame(Dialog)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout.addWidget(self.line)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.pushButton_cancel = QtWidgets.QPushButton(Dialog)
        self.pushButton_cancel.setObjectName("pushButton_cancel")
        self.horizontalLayout.addWidget(self.pushButton_cancel)
        self.pushButton_done = QtWidgets.QPushButton(Dialog)
        self.pushButton_done.setObjectName("pushButton_done")
        self.horizontalLayout.addWidget(self.pushButton_done)
        self.verticalLayout.addLayout(self.horizontalLayout)

        self.retranslateUi(Dialog)
        self.pushButton_cancel.clicked.connect(Dialog.deleteLater)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "Default Signal Settings:"))
        self.label_2.setText(_translate("Dialog", "Pre-EMG window length:"))
        self.label_3.setText(_translate("Dialog", "msec"))
        self.label_5.setText(_translate("Dialog", "Post-EMG window length:"))
        self.label_4.setText(_translate("Dialog", "msec"))
        self.label_6.setText(_translate("Dialog", "Window shape:"))
        self.radioButton_win_shape_tukey.setText(_translate("Dialog", "Tukey"))
        self.radioButton_win_shape_square.setText(_translate("Dialog", "Square"))
        self.radioButton_win_shape_log.setText(_translate("Dialog", "Log"))
        self.pushButton_cancel.setText(_translate("Dialog", "Cancel"))
        self.pushButton_done.setText(_translate("Dialog", "Done"))
