# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI_files/ui_mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1086, 702)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.lineEdit_directory = QtWidgets.QLineEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_directory.sizePolicy().hasHeightForWidth())
        self.lineEdit_directory.setSizePolicy(sizePolicy)
        self.lineEdit_directory.setObjectName("lineEdit_directory")
        self.horizontalLayout.addWidget(self.lineEdit_directory)
        self.toolButton_directory = QtWidgets.QToolButton(self.centralwidget)
        self.toolButton_directory.setObjectName("toolButton_directory")
        self.horizontalLayout.addWidget(self.toolButton_directory)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_9.addWidget(self.label_8)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.radioButton_carto = QtWidgets.QRadioButton(self.centralwidget)
        self.radioButton_carto.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.radioButton_carto.setChecked(True)
        self.radioButton_carto.setObjectName("radioButton_carto")
        self.buttonGroup_2 = QtWidgets.QButtonGroup(MainWindow)
        self.buttonGroup_2.setObjectName("buttonGroup_2")
        self.buttonGroup_2.addButton(self.radioButton_carto)
        self.horizontalLayout_8.addWidget(self.radioButton_carto)
        self.radioButton_other = QtWidgets.QRadioButton(self.centralwidget)
        self.radioButton_other.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.radioButton_other.setObjectName("radioButton_other")
        self.buttonGroup_2.addButton(self.radioButton_other)
        self.horizontalLayout_8.addWidget(self.radioButton_other)
        self.horizontalLayout_9.addLayout(self.horizontalLayout_8)
        self.verticalLayout.addLayout(self.horizontalLayout_9)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.verticalLayout.addLayout(self.horizontalLayout_10)
        self.progressBar = QtWidgets.QProgressBar(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.progressBar.sizePolicy().hasHeightForWidth())
        self.progressBar.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.progressBar.setFont(font)
        self.progressBar.setProperty("value", 0)
        self.progressBar.setObjectName("progressBar")
        self.verticalLayout.addWidget(self.progressBar)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_7.addWidget(self.label_5)
        self.scrollArea_found_studies = QtWidgets.QScrollArea(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scrollArea_found_studies.sizePolicy().hasHeightForWidth())
        self.scrollArea_found_studies.setSizePolicy(sizePolicy)
        self.scrollArea_found_studies.setWidgetResizable(True)
        self.scrollArea_found_studies.setObjectName("scrollArea_found_studies")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 158, 68))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.scrollArea_Vlayout = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.scrollArea_Vlayout.setObjectName("scrollArea_Vlayout")
        self.scrollArea_found_studies.setWidget(self.scrollAreaWidgetContents)
        self.horizontalLayout_7.addWidget(self.scrollArea_found_studies)
        self.verticalLayout.addLayout(self.horizontalLayout_7)
        self.pushButton_extract_data = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_extract_data.setObjectName("pushButton_extract_data")
        self.verticalLayout.addWidget(self.pushButton_extract_data)
        self.line_2 = QtWidgets.QFrame(self.centralwidget)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.verticalLayout.addWidget(self.line_2)
        self.label_11 = QtWidgets.QLabel(self.centralwidget)
        self.label_11.setObjectName("label_11")
        self.verticalLayout.addWidget(self.label_11)
        self.treeView_casesDir = QtWidgets.QTreeView(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.treeView_casesDir.sizePolicy().hasHeightForWidth())
        self.treeView_casesDir.setSizePolicy(sizePolicy)
        self.treeView_casesDir.setObjectName("treeView_casesDir")
        self.verticalLayout.addWidget(self.treeView_casesDir)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.pushButton_delete_study = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_delete_study.setObjectName("pushButton_delete_study")
        self.horizontalLayout_5.addWidget(self.pushButton_delete_study)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem)
        self.pushButton_import_study = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_import_study.setObjectName("pushButton_import_study")
        self.horizontalLayout_5.addWidget(self.pushButton_import_study)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_11.addLayout(self.verticalLayout)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_4.addWidget(self.label_2)
        spacerItem1 = QtWidgets.QSpacerItem(148, 22, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem1)
        self.label_graph_position = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_graph_position.setFont(font)
        self.label_graph_position.setAlignment(QtCore.Qt.AlignCenter)
        self.label_graph_position.setObjectName("label_graph_position")
        self.horizontalLayout_4.addWidget(self.label_graph_position)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem2)
        self.comboBox_signal_type = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_signal_type.setObjectName("comboBox_signal_type")
        self.horizontalLayout_4.addWidget(self.comboBox_signal_type)
        self.spinBox_signals = QtWidgets.QSpinBox(self.centralwidget)
        self.spinBox_signals.setMinimum(1)
        self.spinBox_signals.setMaximum(12000)
        self.spinBox_signals.setObjectName("spinBox_signals")
        self.horizontalLayout_4.addWidget(self.spinBox_signals)
        self.verticalLayout_4.addLayout(self.horizontalLayout_4)
        self.widget_graph = QtWidgets.QWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_graph.sizePolicy().hasHeightForWidth())
        self.widget_graph.setSizePolicy(sizePolicy)
        self.widget_graph.setMinimumSize(QtCore.QSize(800, 250))
        self.widget_graph.setObjectName("widget_graph")
        self.verticalLayout_graph_holder = QtWidgets.QVBoxLayout(self.widget_graph)
        self.verticalLayout_graph_holder.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_graph_holder.setObjectName("verticalLayout_graph_holder")
        self.verticalLayout_4.addWidget(self.widget_graph)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_2.addWidget(self.label_3)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_6.addWidget(self.label_4)
        self.radioButton = QtWidgets.QRadioButton(self.centralwidget)
        self.radioButton.setChecked(True)
        self.radioButton.setObjectName("radioButton")
        self.buttonGroup_3 = QtWidgets.QButtonGroup(MainWindow)
        self.buttonGroup_3.setObjectName("buttonGroup_3")
        self.buttonGroup_3.addButton(self.radioButton)
        self.horizontalLayout_6.addWidget(self.radioButton)
        self.radioButton_2 = QtWidgets.QRadioButton(self.centralwidget)
        self.radioButton_2.setObjectName("radioButton_2")
        self.buttonGroup_3.addButton(self.radioButton_2)
        self.horizontalLayout_6.addWidget(self.radioButton_2)
        self.radioButton_3 = QtWidgets.QRadioButton(self.centralwidget)
        self.radioButton_3.setObjectName("radioButton_3")
        self.buttonGroup_3.addButton(self.radioButton_3)
        self.horizontalLayout_6.addWidget(self.radioButton_3)
        self.line_3 = QtWidgets.QFrame(self.centralwidget)
        self.line_3.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.horizontalLayout_6.addWidget(self.line_3)
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_6.addWidget(self.label_6)
        self.radioButton_EMG_edit_add = QtWidgets.QRadioButton(self.centralwidget)
        self.radioButton_EMG_edit_add.setObjectName("radioButton_EMG_edit_add")
        self.buttonGroup = QtWidgets.QButtonGroup(MainWindow)
        self.buttonGroup.setObjectName("buttonGroup")
        self.buttonGroup.addButton(self.radioButton_EMG_edit_add)
        self.horizontalLayout_6.addWidget(self.radioButton_EMG_edit_add)
        self.radioButton_EMG_edit_delete = QtWidgets.QRadioButton(self.centralwidget)
        self.radioButton_EMG_edit_delete.setObjectName("radioButton_EMG_edit_delete")
        self.buttonGroup.addButton(self.radioButton_EMG_edit_delete)
        self.horizontalLayout_6.addWidget(self.radioButton_EMG_edit_delete)
        self.radioButton_EMG_edit_on = QtWidgets.QRadioButton(self.centralwidget)
        self.radioButton_EMG_edit_on.setObjectName("radioButton_EMG_edit_on")
        self.buttonGroup.addButton(self.radioButton_EMG_edit_on)
        self.horizontalLayout_6.addWidget(self.radioButton_EMG_edit_on)
        self.radioButton_EMG_edit_off = QtWidgets.QRadioButton(self.centralwidget)
        self.radioButton_EMG_edit_off.setChecked(True)
        self.radioButton_EMG_edit_off.setObjectName("radioButton_EMG_edit_off")
        self.buttonGroup.addButton(self.radioButton_EMG_edit_off)
        self.horizontalLayout_6.addWidget(self.radioButton_EMG_edit_off)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem3)
        self.verticalLayout_2.addLayout(self.horizontalLayout_6)
        self.verticalLayout_4.addLayout(self.verticalLayout_2)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_3.addWidget(self.label_7)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem4)
        self.spinBox_geometry = QtWidgets.QSpinBox(self.centralwidget)
        self.spinBox_geometry.setObjectName("spinBox_geometry")
        self.horizontalLayout_3.addWidget(self.spinBox_geometry)
        self.verticalLayout_3.addLayout(self.horizontalLayout_3)
        self.visPy_holder = QtWidgets.QWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.visPy_holder.sizePolicy().hasHeightForWidth())
        self.visPy_holder.setSizePolicy(sizePolicy)
        self.visPy_holder.setMinimumSize(QtCore.QSize(0, 250))
        self.visPy_holder.setObjectName("visPy_holder")
        self.vispy_layout = QtWidgets.QVBoxLayout(self.visPy_holder)
        self.vispy_layout.setContentsMargins(0, 0, 0, 0)
        self.vispy_layout.setObjectName("vispy_layout")
        self.verticalLayout_3.addWidget(self.visPy_holder)
        self.verticalLayout_4.addLayout(self.verticalLayout_3)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem5)
        self.pushButton_export_data = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_export_data.setObjectName("pushButton_export_data")
        self.horizontalLayout_2.addWidget(self.pushButton_export_data)
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.horizontalLayout_2.addWidget(self.line)
        self.pushButton_close = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_close.setObjectName("pushButton_close")
        self.horizontalLayout_2.addWidget(self.pushButton_close)
        self.verticalLayout_4.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_11.addLayout(self.verticalLayout_4)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1086, 22))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuEdit = QtWidgets.QMenu(self.menubar)
        self.menuEdit.setObjectName("menuEdit")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuEdit.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "SignalXtor"))
        self.label.setText(_translate("MainWindow", "Directory path:"))
        self.toolButton_directory.setText(_translate("MainWindow", "..."))
        self.label_8.setText(_translate("MainWindow", "Mapping system:"))
        self.radioButton_carto.setText(_translate("MainWindow", "CARTO"))
        self.radioButton_other.setText(_translate("MainWindow", "Other"))
        self.label_5.setText(_translate("MainWindow", "Found studies:"))
        self.pushButton_extract_data.setText(_translate("MainWindow", "Extract study data"))
        self.label_11.setText(_translate("MainWindow", "Studies directory:"))
        self.pushButton_delete_study.setText(_translate("MainWindow", "Delete study"))
        self.pushButton_import_study.setText(_translate("MainWindow", "Import study"))
        self.label_2.setText(_translate("MainWindow", "Signals:"))
        self.label_graph_position.setText(_translate("MainWindow", "__(mV) - __(msec)"))
        self.label_3.setText(_translate("MainWindow", "Filtering:"))
        self.label_4.setText(_translate("MainWindow", "EMG point type:"))
        self.radioButton.setText(_translate("MainWindow", "Stim"))
        self.radioButton_2.setText(_translate("MainWindow", "QRS"))
        self.radioButton_3.setText(_translate("MainWindow", "Activation"))
        self.label_6.setText(_translate("MainWindow", "Action:"))
        self.radioButton_EMG_edit_add.setText(_translate("MainWindow", "Add"))
        self.radioButton_EMG_edit_delete.setText(_translate("MainWindow", "Delete"))
        self.radioButton_EMG_edit_on.setText(_translate("MainWindow", "Edit"))
        self.radioButton_EMG_edit_off.setText(_translate("MainWindow", "Off"))
        self.label_7.setText(_translate("MainWindow", "Geometry:"))
        self.pushButton_export_data.setText(_translate("MainWindow", "Export data"))
        self.pushButton_close.setText(_translate("MainWindow", "Close"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuEdit.setTitle(_translate("MainWindow", "Edit"))
